language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest
env:
  global:
  - secure: Dg/HUgmSpWvFpbLSr/SI5x6sI+Np9UqZZ9oZwMXXcggFDF9ze4f1W2R8388NEYfM14Sluy7EVCwoYIHiA4Q20FUq1eJCRYMSsd9z/rWmjWpiQ2xhXAjijtJBaf5SRbM45zcoj92wCyojmLT2tcF0OOI1YDpRATL7/Fw2TgiY6RL6QKz+aLPtzGzgFb6DmEDFmPh5lhL0OBy7WRIoK5JxToF284xJ1of1tz4PktPQZ8uB9lhyDlCUoeBei+rwgNm7aM40Dms/hClw3Z3BDgfGdKgB+FQ98T33DCVfGJR3rwc8dFRiBv8sXkrAj5VYmneznSECvdbPG+XXF96sHAntNYoD0TsJCqM2MHcGw9HKuMH13vQfPdt6TAxZ53Rp2DuIe8O0KwkZp0XqlJ88gBw4VHuaGjPZw/dD4fCz+RhAz/XX2i0WxcxZsWZ4l+Sww3Io0Y3HTTSMZ/rkr5Duo0GTeHgJZBYzxVKSWHSMQzu/j3hauAOT7uxrIlQpHuKnLUNurqy4tbfNye6oBx0Po0MQEJ0F7RAXyyt//xycK5bi4Y5jC68sg+UVMfJtcxUNhRb81DqlBSwyyWrBosgn45DuzTtoUEv4/uu9M9kwcMN38SFFdVLj0MXYNbQ+K3pnfBHQT6aUcEg3LAYDSgioD/CXAIl2fEqVOk1wE0hpHR1PXxA=
