language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest
env:
  global:
    secure: H+94YwkwimqtsQqDNeEnHN8Yzrc01BSKT8jkRQfK22PHami8UeWNIjPNHql43ld+ZuKx2lwg1AYmSfN7B6YCG67PHC37+v0Jx6pT0lw0yfknXD0FryYpJsTkP2LL1QmGPm/P1OyluwU8u6LcvkYLiITZlvFeTwK8ceq50hxRvsn/8nmRum4mENpHQuw1az3yu0TSV8ZUPqpuLw6tFi20FFysQGUS2YXPqf9+uMLfJPrPD+Yxqcm92cHwGKAwhQCn3xFlecLuNlVTf0a9FJjK/QCd+p/xpNUsX1DWjx/U0L4zTOYXgVjWuf2CZZp+tC1K4q0K5/dfnwLh/KxJei7aZBVNV+QuibkjxYYXs7RXBkUmOF8iuJX4eKV/d1CwjJNkRKj0Xmr5uvgicCXH2DTNDRwaB7iYcNjEndGbnwBdW2+JWYcsl5e1t5lBm3OrezUcIEInadvyXaaxhwKVT1fvDFS1JOQroInx08iWrALYJ/CCYlb9jvilxE06IyVMfoXceEqoNODllAV2aU77bID33cYOO2uAp6c/BfU6tKIIN31llce9h3Nkp3IvHdpSIXHXcyHWkkziv8gOPrA1nQ2BM5ycoHz9KZyVwbPFujGL13zUkn/2hEy4Olv92QLExrS3T+FQysSkJxk1jYNytCoZoKzkb+TpeA7iAGtfWUwuDqc=
