language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest
env:
  global:
  - secure: ZeV15ANKrwa6P8YJfO+VEEPL3jOzn3Og/VpuQaRBmWoNx2bo/pbWlBJf2OomeN56+BZP+ie+1nJ1+EHO6I4lDqaK/Dc+VTCfE6w+5vvZ3GSksldePbvz0LbudSay6fJ/MhOOnrb7EokVE8IWFFrl5mJ5eVZ752H08e3F3tD8HVfC/FJal9mltD6ps2Zc0DsOmLVxhKz6Qm002ccAujdi0OwR02OPyGh9eLSoxyZdYuhR5lngHe89Q66DPSlpOC//azY5tD/DSUmxmmq4TWVfrgdRxLlp7pOz0hfjRlTqbWKqPOgVP55WynFBsNoMfKG/jbIk/sakEsFiYaY58haPoKdVlVWBlZXm4fCEs1Odmpz5QfpROKD33NCSqEACsWYyIZEkJzpxcXpuhoTA//73PEgtSZW/7rhAJLRfX0+v2kIzdDYMsaQ0P848FEE5mKq/+Qe6di8KA28cV/UCzSjtotLPpgh0bYl19TlpUUnITKLaQAr096iyo3x4MDRsImPwnp49IzhqTRJYoanP/3c8Cz/L+ufULVgkV+EiU1rV4yPnaxD2HsXxIUhQio7Re8/zLRqRVTtTJlidwr6iUMYGuR9Hr8QJtsvE7BQ9MK+Eo2WY0i5M4iSnG/0cjXCgFbo+4qNiyJ/u4iF9iqI2myU0+rjzrcsDgJjKN8xXB1/oEBA=
